# Rate limited (minimum of 3 seconds between requests)
seconds_per_request: 4

# Option to get new, cross-list, or replaced
targets:
  - new
  - cross-list
  - replaced

# Default will be to target all of Computer Science
repositories:
  - cs.AI
  - cs.AR
  - cs.CC
  - cs.CE
  - cs.CG
  - cs.CL
  - cs.CR
  - cs.CV
  - cs.CY
  - cs.DB
  - cs.DC
  - cs.DL
  - cs.DM
  - cs.DS
  - cs.ET
  - cs.FL
  - cs.GL
  - cs.GR
  - cs.GT
  - cs.HC
  - cs.IR
  - cs.IT
  - cs.LG
  - cs.LO
  - cs.MA
  - cs.MM
  - cs.MS
  - cs.NA
  - cs.NE
  - cs.NI
  - cs.OH
  - cs.OS
  - cs.PF
  - cs.PL
  - cs.RO
  - cs.SC
  - cs.SD
  - cs.SE
  - cs.SI
  - cs.SY